import { StyleSheet } from 'react-native';

export default Style = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    viewInput: {
        padding:20,
        borderRadius: 10,
        height: 60,
        width:300,
        flexDirection: 'row',
        backgroundColor: '#DCDCDC',
        alignItems: 'center',
        paddingHorizontal: 10,
        marginBottom:10,
      },
    input: {
        fontSize: 18,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        textAlign: 'center',
        flex: 1,
      },
    texto: {
        color: "#000", 
        textAlign: 'center', 
    },
    textoResultado: {
        color: "#fff", 
        textAlign: 'center', 
    },
    botao: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 10,
        elavation: 3,
        backgroundColor: '#DCDCDC',
        height: 60,
        width: 300,
      },
      botaoResultado: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 10,
        elavation: 3,
        backgroundColor: '#FF00FF',
        marginTop: 10,
        height: 60,
        width: 300,
      },
  });